/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import java.awt.Container;
import java.awt.Image;
import javax.swing.ImageIcon;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.io.File;
import java.sql.Connection;
import java.sql.DriverManager;
import java.util.HashMap;
import java.util.Map;
import javax.swing.JOptionPane;
import models.Department;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.swing.JRViewer;
import net.sf.jasperreports.view.JasperViewer;
import tools.Connections;

/**
 *
 * @author DELL
 */
public class MainView extends javax.swing.JFrame {

    private Image image;
    private Connection connection;
    JasperDesign JasDes;
    JasperReport Jasrep;
    JasperPrint Jaspri;
    Map param = new HashMap();

    /**
     * Creates new form MainView
     */
    public MainView() {
        initComponents();
        this.connection = new Connections().getConnection();
        image = new ImageIcon(getClass().getResource("bg.jpg")).getImage();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenu3 = new javax.swing.JMenu();
        dskHR = new javax.swing.JDesktopPane();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        mnRegion = new javax.swing.JMenuItem();
        mnEmployee = new javax.swing.JMenuItem();
        mnJob = new javax.swing.JMenuItem();
        mnLocation = new javax.swing.JMenuItem();
        mnDepartment = new javax.swing.JMenuItem();
        mnCountry = new javax.swing.JMenuItem();
        MenuReport = new javax.swing.JMenu();
        ReportRegion = new javax.swing.JMenuItem();
        ReportEmployee = new javax.swing.JMenuItem();
        ReportDep = new javax.swing.JMenuItem();

        jMenu3.setText("jMenu3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HR SYSTEM");

        dskHR.setBackground(getBackground());

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/views/bg4.jpg"))); // NOI18N
        jLabel2.setText("jLabel2");
        dskHR.add(jLabel2);
        jLabel2.setBounds(0, 0, 920, 710);

        jMenuBar1.setBackground(new java.awt.Color(0, 153, 255));
        jMenuBar1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, java.awt.Color.lightGray, java.awt.Color.gray, java.awt.Color.darkGray, java.awt.Color.gray));

        jMenu1.setText("File");

        mnRegion.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.ALT_MASK));
        mnRegion.setText("Region");
        mnRegion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnRegionActionPerformed(evt);
            }
        });
        jMenu1.add(mnRegion);

        mnEmployee.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
        mnEmployee.setText("Employee");
        mnEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnEmployeeActionPerformed(evt);
            }
        });
        jMenu1.add(mnEmployee);

        mnJob.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_J, java.awt.event.InputEvent.CTRL_MASK));
        mnJob.setText("Job");
        mnJob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnJobActionPerformed(evt);
            }
        });
        jMenu1.add(mnJob);

        mnLocation.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_L, java.awt.event.InputEvent.CTRL_MASK));
        mnLocation.setText("Location");
        mnLocation.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnLocationActionPerformed(evt);
            }
        });
        jMenu1.add(mnLocation);

        mnDepartment.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_D, java.awt.event.InputEvent.CTRL_MASK));
        mnDepartment.setText("Department");
        mnDepartment.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnDepartmentActionPerformed(evt);
            }
        });
        jMenu1.add(mnDepartment);

        mnCountry.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
        mnCountry.setText("Country");
        mnCountry.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mnCountryActionPerformed(evt);
            }
        });
        jMenu1.add(mnCountry);

        jMenuBar1.add(jMenu1);

        MenuReport.setText("Report");

        ReportRegion.setText("Region ");
        ReportRegion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReportRegionActionPerformed(evt);
            }
        });
        MenuReport.add(ReportRegion);

        ReportEmployee.setText("Employee");
        ReportEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReportEmployeeActionPerformed(evt);
            }
        });
        MenuReport.add(ReportEmployee);

        ReportDep.setText("Department");
        ReportDep.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ReportDepActionPerformed(evt);
            }
        });
        MenuReport.add(ReportDep);

        jMenuBar1.add(MenuReport);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(dskHR, javax.swing.GroupLayout.PREFERRED_SIZE, 837, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(51, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(dskHR, javax.swing.GroupLayout.PREFERRED_SIZE, 627, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(40, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mnRegionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnRegionActionPerformed
        // TODO add your handling code here:
        RegionsView regionsView = new RegionsView();
        regionsView.show();
        dskHR.add(regionsView);
    }//GEN-LAST:event_mnRegionActionPerformed

    private void mnEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnEmployeeActionPerformed
        EmployeesView employeesView = new EmployeesView();
        employeesView.show();
        dskHR.add(employeesView);
    }//GEN-LAST:event_mnEmployeeActionPerformed

    private void mnJobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnJobActionPerformed
        // TODO add your handling code here:
        JobsView jobsView = new JobsView();
        jobsView.show();
        dskHR.add(jobsView);
    }//GEN-LAST:event_mnJobActionPerformed

    private void mnLocationActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnLocationActionPerformed
        // TODO add your handling code here:
        Locations locations = new Locations();
        locations.show();
        dskHR.add(locations);
    }//GEN-LAST:event_mnLocationActionPerformed

    private void mnDepartmentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnDepartmentActionPerformed

    }//GEN-LAST:event_mnDepartmentActionPerformed

    private void mnCountryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mnCountryActionPerformed
        // TODO add your handling code here:
        Country country = new Country();
        country.show();
        dskHR.add(country);
    }//GEN-LAST:event_mnCountryActionPerformed

    private void ReportRegionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReportRegionActionPerformed
        ReportView reportView = new ReportView("Region");
        reportView.show();
        dskHR.add(reportView);
    }//GEN-LAST:event_ReportRegionActionPerformed

    private void ReportEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReportEmployeeActionPerformed
        ReportView reportView = new ReportView("Region_1");
        reportView.show();
        dskHR.add(reportView);
    }//GEN-LAST:event_ReportEmployeeActionPerformed

    private void ReportDepActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ReportDepActionPerformed
        ReportView reportView=new ReportView("Departments");
        reportView.show();
        dskHR.add(reportView);
    }//GEN-LAST:event_ReportDepActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu MenuReport;
    private javax.swing.JMenuItem ReportDep;
    private javax.swing.JMenuItem ReportEmployee;
    private javax.swing.JMenuItem ReportRegion;
    private javax.swing.JDesktopPane dskHR;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem mnCountry;
    private javax.swing.JMenuItem mnDepartment;
    private javax.swing.JMenuItem mnEmployee;
    private javax.swing.JMenuItem mnJob;
    private javax.swing.JMenuItem mnLocation;
    private javax.swing.JMenuItem mnRegion;
    // End of variables declaration//GEN-END:variables
}
